import struct
import olexparser.convert as convert


class SegmentEntry:
    """
    A class representing a 16 byte entry from a segment file

    Each segment file consists of a number of 16 byte entries.
    Each entry contains a unix timestamp, latitude coordinate, longitude coordinate, and 4 bytes of unknown purpose.
    The unix timestamp is stored as a 4 byte integer. The latitude and longitude are stored as 4 byte floats.

    """

    def __init__(self, entry):
        """A constructor method for the SegmentEntry.

        :param entry: the 16 bytes which constitute an entry in the segment file
        :type entry: bytes
        .. todo:: add error handling for failed byte conversions
        """

        self.warnings = []
        if len(entry) != 16:
            warn = "Error, Segment Entry is not 16 byte length"
            self.warnings.append(warn)
        else:
            # convert the bytes into an int.
            self.timestamp_int = int.from_bytes(entry[:4], "little")

            # convert the bytes into a float
            self.lat_float = struct.unpack('f', entry[4:8])[0]

            # convert the bytes into a float
            self.long_float = struct.unpack('f', entry[8:12])[0]

            # store the 4 unknown bytes as bytes
            self.unknown = entry[12:]

    def __str__(self):
        """A descriptive String representation of the SegmentEntry.

        :return: A descriptive string with known values converted.
        :rtype: str
        """
        s = "\nUnix Timestamp: {} Timestamp converted UTC: {}".format(
            self.timestamp_int, convert.get_timestamp_str_from_int(self.timestamp_int))
        s = s + "\nLatitude float: {} Latitude coordinate: {}".format(
            self.lat_float, convert.get_lat_dmm(self.lat_float))
        s = s + "\nLongitude float: {} Longitude coordinate: {}".format(
            self.long_float, convert.get_long_dmm(self.long_float))
        s = s + "\n4 bytes of unknown purpose: {}".format(self.unknown)
        return s

    def print_segment_entry(self):
        """Prints the converted data from the 16 bytes"""
        print("Unix Timestamp: {} Timestamp converted UTC: {}".format(
            self.timestamp_int, convert.get_timestamp_str_from_int(self.timestamp_int)))
        print("Latitude float: {} Latitude coordinate: {}".format(
            self.lat_float, convert.get_lat_dmm(self.lat_float)))
        print("Longitude float: {} Longitude coordinate: {}".format(
            self.long_float, convert.get_long_dmm(self.long_float)))
        print("4 bytes of unknown purpose: {}".format(self.unknown))
        return

    def get_lat_float(self):
        """
        :return float: the 'Olex float' representing a latitude coordinate
        :rtype: float

        """
        return self.lat_float

    def get_long_float(self):
        """
        :return: the 'Olex float' representing a longitude coordinate
        :rtype: float

        """
        return self.long_float

    def get_unknown(self):
        """
        :return: The 4 unknown bytes at the end of an entry.
        :rtype: bytes

        """
        return self.unknown

    def get_timestamp_int(self):
        """
        :return: the integer representing a unix timestamp
        :rtype: int
        """
        return self.timestamp_int

    def get_warnings(self):
        """
        :return: A list of warnings generated by the SegmentEntry
        :rtype: list
        """
        return self.warnings
